#pragma once

#include "MenuRegistry.h"
#include "GameState.h"
#include "Command.h"
#include <string>
#include <vector>

class MenuController
{
public:
	MenuController(MenuRegistry& menuRegistry, GameState& gameState);

	// set the current menu by name
	void setCurrentMenu(const std::string& menuName);

	// display the current menu
	void displayCurrentMenu(size_t selectedIndex) const;

	// process the user's input
	void processInput(size_t choice);

	// getter for menu name
	const std::string& getCurrentMenuName() const;

private:
	void executeCommands(const std::vector<Command>& commands); // executes a list of commands generated by MenuOption

	MenuRegistry& menuRegistry;                                 // reference to the menu registry
	GameState& gameState;                                       // reference to the game state
	std::string currentMenuName;
};